### ISSUE TITLE
是否有直接html使用的示例

### ISSUE THREAD

**Issue by ganpanlin** [Kuaizi-co/TreeManager#1]
如题：是否有直接html使用的示例

**Comment by tomieric** [comment]
官网已经新版本已经添加相关的实例了[http://element.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong](http://element.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong)

**Comment by ganpanlin** [comment]
感谢！
